plugin_group:
  - !include "plugins/debugview.yaml"
  - !include "plugins/gldemo.yaml"
  - !include "plugins/timewarp_gl.yaml"
  - !include "plugins/offline_imu_cam.yaml"
  - !include "plugins/monado_integration.yaml"
  - !include "plugins/monado_mainline.yaml"
  - !include "plugins/monado_openxr_app.yaml"
  - !include "plugins/pose_lookup.yaml"
  - !include "plugins/realsense.yaml"
