plugin_group:
  - !include "plugins/gtsam_integrator.yaml"
  - !include "plugins/kimera-vio.yaml"
  - !include "plugins/offline_imu_cam.yaml"
  - !include "plugins/offload_data.yaml"
  - !include "plugins/openvins.yaml"
  - !include "plugins/pose_prediction.yaml"
  - !include "plugins/rk4_integrator.yaml"
