##
## Configuration to run CI flows (see 'configs/ci')
##

action:
  name: tests

  kimera_path: !include "data/kimera-default.yaml"
  audio_path:  !include "data/audio-default.yaml"

  enable_ci:  True
  run-solo:   !include "ci/run-solo.yaml"
  build-only: !include "ci/build-only.yaml"
  no-build:   !include "ci/no-build.yaml"

common:    !include "plugins/common.yaml"
runtime:   !include "plugins/runtime.yaml"
data:      !include "data/euroc-default.yaml"
demo_data: !include "data/demo-default.yaml"

profile: dbg

flows:
  - !include "ci/flows/lookup.yaml"
  - !include "ci/flows/openvins-rk4.yaml"
  - !include "ci/flows/openvins-gtsam.yaml"
  - !include "ci/flows/kimera-rk4.yaml"
  - !include "ci/flows/kimera-gtsam.yaml"
