##
## Configuration to `make clean` all plugins listed below
##
plugin_groups:
  - !include "all_plugins.yaml"

action:
  name: clean

## Unused definitions
profile: opt
data: data
demo_data: demo_data
enable_offload: False
enable_alignment: False
enable_verbose_errors: False
