##
## Configuration to `make clean` all plugins listed below
##

action:
  name: clean

common:    !include "plugins/common.yaml"
runtime:   !include "plugins/runtime.yaml"
data:      !include "data/data-default.yaml"
demo_data: !include "data/demo-default.yaml"

flows:
  - flow:
    - !include "plugins/groups/all.yaml"
