# Run with ground truth pose lookup instead of pose prediction
plugin_groups:
  - plugin_group:
      - path: pose_lookup
      - path: timewarp_gl/
      - path: gldemo/
data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  name: native
  command: ./apitrace trace --output=trace %a
  ILLIXR_RUN_DURATION: 30
profile: opt
