##
## Configuration to run integrated ILLIXR with a virtual framebuffer
##

action:
  name: native

  kimera_path: !include "data/kimera-default.yaml"

  command: xvfb-run %a

common:    !include "plugins/common.yaml"
runtime:   !include "plugins/runtime.yaml"
data:      !include "data/euroc-default.yaml"
demo_data: !include "data/demo-default.yaml"

profile: opt

flows:
  - !include "ci/flows/kimera-gtsam.yaml"
