plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"
  - plugin_group:
    - path: ground_truth_slam/
    - path: gldemo/

loader:
  name: native
  command: xvfb-run %a
profile: opt

constants:
  - !include "global_module_defs.yaml"
