plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"

# realsense_cam: auto

action:
  name        : monado
  is_mainline : False

  monado:
    path:
      git_repo : https://github.com/ILLIXR/monado_integration.git
      version  : "3.0"

    config: # For CMake
      BUILD_WITH_LIBUDEV : "0"
      BUILD_WITH_LIBUSB  : "0"
      BUILD_WITH_LIBUVC  : "0"
      BUILD_WITH_NS      : "0"
      BUILD_WITH_PSMV    : "0"
      BUILD_WITH_PSVR    : "0"
      BUILD_WITH_OPENHMD : "0"
      BUILD_WITH_VIVE    : "0"

  openxr_app: !include "openxr_app.yaml"

  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO.git/
  audio_path:  .cache/paths/https%c%s%sgithub.com%sILLIXR%saudio_pipeline.git/

profile: opt

constants:
  - !include "global_module_defs.yaml"
