plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"

enable_offload:   False
enable_alignment: False
enable_verbose_errors: False
enable_pre_sleep: False
# realsense_cam: auto

action:
  name: monado
  monado:
    path:
      git_repo: https://github.com/ILLIXR/monado_integration.git
      version: "3.0"
  openxr_app:
    path:
      git_repo: https://github.com/ILLIXR/Monado_OpenXR_Simple_Example.git
      version: "3.0"
    config: {}
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  

profile: opt

constants:
  - !include "global_module_defs.yaml"
