##
## Configuration to run integrated ILLIXR with Monado
##

action:
  name: monado
  is_mainline : False

  kimera_path: !include "data/kimera-default.yaml"
  audio_path:  !include "data/audio-default.yaml"
  monado:      !include "plugins/monado_integration.yaml"
  openxr_app:  !include "plugins/monado_openxr_app.yaml"

common:    !include "plugins/common.yaml"
runtime:   !include "plugins/runtime.yaml"
data:      !include "data/data-default.yaml"
demo_data: !include "data/demo-default.yaml"

profile: opt

flows:
  - flow:
    - !include "plugins/groups/rt_slam.yaml"
    - !include "plugins/groups/kimera-gtsam.yaml"
    - !include "plugins/groups/core.yaml"
