plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"

loader:
  name: monado
  monado:
    path:
      git_repo: https://github.com/ILLIXR/monado_integration.git
      version: master
  openxr_app:
    path:
      git_repo: https://github.com/ILLIXR/Monado_OpenXR_Simple_Example.git
      version: master
    config: {}
profile: opt

constants:
  - !include "global_module_defs.yaml"
