##
## Configuration to run integrated ILLIXR with Monado
##

action:
  name: monado

  kimera_path: !include "data/kimera-default.yaml"
  monado:      !include "plugins/monado_integration.yaml"
  openxr_app:  !include "plugins/monado_openxr_app.yaml"

common:    !include "plugins/common.yaml"
runtime:   !include "plugins/runtime.yaml"
data:      !include "data/euroc-default.yaml"
demo_data: !include "data/demo-default.yaml"

profile: opt

flows:
  - flow:
    - !include "plugins/groups/rt_slam.yaml"
    - !include "plugins/groups/kimera-gtsam.yaml"
    - !include "plugins/groups/core.yaml"
