plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - !include "core_plugins.yaml"
  - plugin_group:
    - path: ground_truth_slam/
    - path: gldemo/
    - path: debugview/

loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native
  # command: gdb -q --args %a
profile: opt

constants:
  - !include "global_module_defs.yaml"
