plugin_groups:
<<<<<<< HEAD
  - plugin_group:
    - path: ../robotics_project/scheduler_plugin/
=======
  # - plugin_group:
  #   - path: ../robotics_project/scheduler_plugin/
>>>>>>> 226ecd08... Added global clock
      # This has to go first because the n_thread_start queue needs to be listening
      # when the other plugins actually start up
  - !include "rt_slam_plugins.yaml"
  - plugin_group:
    - path: gldemo/
      # threadloop, by scheduler
    # - path: debugview/
  - !include "core_plugins.yaml"
  - plugin_group:
    - path: offline_cam/
<<<<<<< HEAD
    # - path: debugview/
=======
    - path: debugview/
>>>>>>> 226ecd08... Added global clock

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native

  # run in GDB:
<<<<<<< HEAD
  # command: env ILLIXR_IGNORE_SCHED_SETSCHEDULER=y gdb -q --args $cmd
=======
  # command: gdb -q --args $cmd
>>>>>>> 226ecd08... Added global clock

  # print cmd for external use:
  # command: printf %s\n $env_cmd

  # command: env ILLIXR_STDOUT_METRICS=y $cmd

<<<<<<< HEAD
  command: sudo taskset -a -c 0 gdb -q --args $env_cmd
=======
  # command: sudo taskset -a -c 0 gdb -q --args $env_cmd
>>>>>>> 226ecd08... Added global clock

  # log_stdout: metrics/output.log
  # command: sudo taskset -a -c 0 env ILLIXR_STDOUT_METRICS=y $env_cmd

<<<<<<< HEAD
=======
  # command: sudo taskset -a -c 0 $env_cmd

  # command: $env_cmd

>>>>>>> 226ecd08... Added global clock
profile: opt
