plugin_groups:
  - plugin_group:

      # This has to go first because the n_thread_start queue needs to be listening
      # when the other plugins actually start up

    - path: gtsam_integrator/

    - path: pose_prediction/

    - path: offline_imu/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native

  # run in GDB:
  # command: sudo gdb -q --args env ASAN_OPTIONS=new_delete_type_mismatch=0 ILLIXR_RUN_DURATION=10 $env_cmd

  # command: printf "%s " $env_cmd
  command: env ILLIXR_RUN_DURATION=10 $env_cmd

  # cpu_freq_ghz: 5.3

  # log_stdout: scheduled.log
  # command: sudo taskset -a -c 0 env ILLIXR_STDOUT_METRICS=y $env_cmd

profile: opt
