plugin_groups:
  - plugin_group:
    - path: ../robotics_project/scheduler_plugin/
      # This has to go first because the n_thread_start queue needs to be listening
      # when the other plugins actually start up
    # - path: zed/
    - path: ../open_vins
    - path: dummy/
    - path: pose_prediction/
    # - path: pose_lookup/
    - path: gldemo/
    - path: timewarp_gl/
    # - path: dummy/
    - path: debugview/
    - path: offline_imu/
    - path: offline_cam/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native

  # run in GDB:
  # command: gdb -q --args $cmd
  # command: sudo taskset -a -c 0 gdb -q --args env __GL_SYNC_TO_VBLANK=0 __GL_MaxFramesAllowed=2 $env_cmd

  # command: sudo taskset -a -c 0 gdb -q --args $env_cmd

  command: sudo taskset -a -c 0 $env_cmd

  # log_stdout: metrics/output.log
  # command: sudo taskset -a -c 0 env ILLIXR_STDOUT_METRICS=y $env_cmd

profile: opt
