plugin_groups:
  - plugin_group:

    # - path: dummy/
    - path: ../robotics_project/scheduler_plugin/
      # This has to go first because the n_thread_start queue needs to be listening
      # when the other plugins actually start up

    - path: ../open_vins/

    - path: gtsam_integrator/

    - path: pose_prediction/
    # - path: pose_lookup/

    - path: gldemo/

    - path: timewarp_gl/

    - path: offline_imu/
    - path: offline_cam/
    # - path: zed/

    # - path: debugview/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native

  # run in GDB:
  # command: sudo gdb -q --args taskset -a -c 0 env ILLIXR_RUN_DURATION=10 ILLIXR_SCHEDULER=y $env_cmd
  command: env ILLIXR_RUN_DURATION=20 ILLIXR_SCHEDULER=y $env_cmd
  # ILLIXR_SCHEDULER=y 
  # command: rm -rf /home/grayson5/ILLIXR-analysis/.cache && taskset -a -c 0 env ILLIXR_RUN_DURATION=30 ILLIXR_SCHEDULER=y $env_cmd

  # command: printf "%s " $env_cmd
  # command: sudo taskset -a -c 0 env ILLIXR_RUN_DURATION=40 ILLIXR_SCHEDULER=y $env_cmd
  # __GL_MaxFramesAllowed=1 __GL_SYNC_TO_VBLANK=1
  # ILLIXR_SCHEDULER=y
  # command: env ILLIXR_RUN_DURATION=40 $env_cmd

  cpu_freq_ghz: 1.3

  scheduler: yes

  duration: 20

  cpu_list: "0"

  gdb: no

  sudo: yes

  # log_stdout: scheduled.log
  # command: sudo taskset -a -c 0 env ILLIXR_STDOUT_METRICS=y $env_cmd

profile: opt
