# Run with ground truth pose lookup instead of pose prediction
plugin_groups:
  - plugin_group:
      - path: pose_lookup
  - !include "core_plugins.yaml"
  - plugin_group:
    - path: gldemo/
    - path: debugview/

loader:
  name: native
  # command: gdb -q --args %a
profile: opt

constants:
  - !include "global_module_defs.yaml"
