plugin_groups:
  - !include "rt_slam_plugins.yaml"
  - plugin_group:
    - path: gldemo/
      # threadloop, by scheduler
    # - path: debugview/
  - !include "core_plugins.yaml"
  - plugin_group:
    - path: ../robotics_project/scheduler_plugin/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native

  # command: sudo $env_cmd

  # run in GDB:
  # command: gdb -q --args $cmd

  # print cmd for external use:
  # command: printf %s\n $env_cmd

  # command: env ILLIXR_STDOUT_METRICS=y $cmd

  # log_stdout: metrics/output.log

profile: opt
