# Run with ground truth pose lookup instead of pose prediction
plugin_groups:
  - plugin_group:
    - path: pose_lookup
    - path: gldemo/
    - path: debugview/
    - path: offload_data/
  - !include "core_plugins.yaml"

enable_offload:   False
enable_alignment: False
enable_verbose_errors: False
enable_pre_sleep: False

action:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native

  # run in GDB:
  # command: gdb -q --args $cmd

  # Print cmd for external use:
  # command: printf %s\n $env_cmd

  # Capture stdout for metrics
  # log_stdout: metrics/output.log

profile: opt

constants:
  - !include "global_module_defs.yaml"
