plugin_groups:
  - plugin_group:

    # - path: dummy/
    - path: ../robotics_project/scheduler_plugin/
      # This has to go first because the n_thread_start queue needs to be listening
      # when the other plugins actually start up

    - path: ../open_vins/

    - path: gtsam_integrator/

    - path: pose_prediction/
    # - path: pose_lookup/

    - path: gldemo/

    - path: timewarp_gl/

    - path: offline_imu/
    - path: offline_cam/
    # - path: zed/

    # - path: debugview/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
conditions:
  scheduler: yes
  duration: 20
  cpus: 1
  cpu_freq: 1.3
loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native
  gdb: no
  sudo: yes
  echo: no
  # metrics: metrics/
  # log_stdout: metrics/output
  env:
     __GL_MaxFramesAllowed: "1"
     __GL_SYNC_TO_VBLANK: "1"

  scheduler:
    nodes: {
        "open_vins"       : [{5.3: 18.02,  2.6: 20.17, 1.8: 44.35, 1.3: 20.84}, 0, 0,    0,    ["gtsam_integrator"]],
        "gtsam_integrator": [{5.3:   .1,   2.6:   .2 , 1.8:   .07, 1.3:   .31}, 5, 0,    0,    ["gldemo", "timewarp_gl"]],
        "gldemo"          : [{5.3:   .9,   2.6:  1.04, 1.8:  2.11, 1.3:  1.11}, 0, 0,    0,    ["timewarp_gl"]],
        "timewarp_gl"     : [{5.3:   .9,   2.6:  1.62, 1.8:  2.32, 1.3:  3.  }, 0, 8.33, 8.33, []],
        "offline_imu"     : [{5.3:   .02,  2.6:   .02, 1.8:   .02, 1.3:   .03}, 5, 0,    0,    ["gtsam_integrator", "open_vins"]],
        "offline_cam"     : [{5.3:   .03,  2.6:   .04, 1.8:   .02, 1.3:   .06}, 0, 0,    0,    ["open_vins"]],
    }
    chains: [
        [17, ["offline_imu", "gtsam_integrator", "timewarp_gl"]],
        [22, ["offline_imu", "gtsam_integrator", "gldemo", "timewarp_gl"]],
        [69, ["offline_cam", "open_vins", "timewarp_gl"]],
        [77, ["offline_cam", "open_vins", "gldemo", "timewarp_gl"]],
        [69, ["offline_cam", "open_vins", "gtsam_integrator", "timewarp_gl"]],
        [77, ["offline_cam", "open_vins", "gtsam_integrator", "gldemo", "timewarp_gl"]],
    ]
    constr: true
    fc: {5.3: 3, 2.6: 4, 1.8: 13, 1.3: 6}
    freqs: [5.3, 2.6, 1.8, 1.3]

profile: opt
