plugin_groups:
  - plugin_group:
    # offline dataset options:

    # - path: zed/

    - name: OpenVINS
      path: ../open_vins
    - path: gtsam_integrator/
    - path: pose_prediction/
    # - path: pose_lookup/
    - path: gldemo/
    - path: timewarp_gl/
    - path: debugview/
    # - path: offline_imu_cam/ # -> imu_cam
      # starts the timer when it loads, it sends the very first frame first

    - path: offline_imu/ # cam -> imu_cam
    - path: offline_cam/ # -> cam
      # starts the timer at system load, its ends t+2sec frame first.    

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  kimera_path: .cache/paths/https%c%s%sgithub.com%sILLIXR%sKimera-VIO/
  name: native

  # run in GDB:
  # command: gdb -q --args $cmd

  # print cmd for external use:
  # command: printf %s\n $env_cmd

  # command: sudo taskset -a -c 0 gdb -q --args $env_cmd

  # log_stdout: metrics/output.log
  # command: env ILLIXR_STDOUT_METRICS=y $cmd

  # command: sudo taskset -a -c 0 env ILLIXR_STDOUT_METRICS=y $env_cmd

  # command: taskset -a -c 0 env ILLIXR_RUN_DURATION=100 $env_cmd
  command: env ILLIXR_RUN_DURATION=100 $env_cmd

profile: opt
