app:
  src_path:
    git_repo : https://gitlab.freedesktop.org/monado/demos/openxr-simple-example
    version  : master
#  bin_subpath: build/openxr-example
  bin_subpath: build/Material_Testers.x86_64
#  bin_subpath: build/Sponza_VR.x86_64
config: {}
