plugin_group:
  - path: offline_imu_cam/
  # - path: zed/
  # - path: realsense/
  # - name: Kimera-VIO/
  #   path:
  #     git_repo: https://github.com/ILLIXR/Kimera-VIO
  #     version: "issue-58-standardize-clock"
  - name: OpenVINS
    path: ../open_vins
  #     git_repo: https://github.com/ILLIXR/open_vins.git
  #     version: "issue-58-standardize-clock"
  # - path: gtsam_integrator/
  # - path: rk4_integrator/
  - path: dummy_integrator/
  - path: pose_prediction/
