plugin_group:
  - path: offline_imu/
  # - path: zed/
  # - name: Kimera-VIO/
  #   path:
  #     git_repo: https://github.com/ILLIXR/Kimera-VIO
  #     version: 6ea99d33fc2435a8c514049416dcb2f8a0e31692
  - path: ../open_vins
    # switchboard sync subscribe
  # - path: gtsam_integrator/
  - path: gtsam_integrator/
    # switchboard sync subscribe
  - path: pose_prediction/
    # service, gets called
  # - path: pose_lookup/
