plugin_groups:
  - plugin_group:
    - path: offline_imu_cam/
    - path: open_vins/
    - path: slam_tester/

data:
  subpath: mav0
  relative_to:
    archive_path:
      download_url: 'http://robotics.ethz.ch/~asl-datasets/ijrr_euroc_mav_dataset/vicon_room1/V1_02_medium/V1_02_medium.zip'
demo_data: demo_data/
loader:
  name: native
  # command: gdb -q --args %a
  ILLIXR_RUN_DURATION: 30
profile: dbg
