$schema: http://json-schema.org/schema#
$id: http://illixr.github.io/schemas/config.json
definitions:
  app:
    oneOf:
      - type: string
      - type: object
        additionalProperties: false
        required:
          - src_path
          - bin_subpath
        properties:
          src_path:
            $ref: '#/definitions/path'
            default: {}
            description: Path to source to build
          bin_subpath:
            type: string
            default: ''
            description: Path string of compiled app binary, relative to src_path
  path:
    oneOf:
      - type: string
      - type: object
        additionalProperties: false
        required:
          - git_repo
          - version
        properties:
          git_repo:
            $ref: '#/definitions/path'
            description: Path to repo
          version:
            type: string
            description: Branch, tag, or commit hash
      - type: object
        additionalProperties: false
        required:
          - archive_path
        properties:
          archive_path:
            description: Path to archive
            $ref: '#/definitions/path'
      - type: object
        additionalProperties: false
        required:
          - download_url
        properties:
          download_url:
            type: string
            description: URL to download
      - type: object
        additionalProperties: false
        required:
          - subpath
          - relative_to
        properties:
          subpath:
            type: string
          relative_to:
            $ref: '#/definitions/path'
type: object
additionalProperties: false
properties:
  plugin_groups:
    type: array
    default: []
    items:
      type: object
      additionalProperties: false
      properties:
        plugin_group:
          type: array
          default: []
          items:
            type: object
            additionalProperties: false
            properties:
              name:
                description: An optional name for the plugin
                default: ""
                type: string
              path:
                $ref: '#/definitions/path'
                description: Path to the directory containing the SO.
              config:
                default: {}
                type: object
                additionalProperties:
                  type: string
                description: Vars that get passed to the build system
            required:
              - path
  common:
    default: {}
    type: object
    additionalProperties: false
    properties:
      path:
        default: ./common
        $ref: '#/definitions/path'
        description: Path to https://github.com/ILLIXR/ILLIXR
  runtime:
    default: {}
    type: object
    additionalProperties: false
    properties:
      path:
        default: ./runtime
        $ref: '#/definitions/path'
        description: Path to https://github.com/ILLIXR/ILLIXR
      config:
        default: {}
        type: object
        additionalProperties:
          type: string
        description: Vars that get passed to the build system
  action:
    type: object
    additionalProperties: true
    default: {}
    required:
      - name
    properties:
      name:
        default: native
        type: string
        description: "Currently supports: 'native', 'monado', 'tests', or 'clean'"
        properties:
          path:
            $ref: '#/definitions/path'
            description: Path to action
      config:
        default: {}
        type: object
        additionalProperties:
          type: string
        description: Interpretation of these vars is action-dependent
      openxr_app:
        default: {}
        type: object
        additionalProperties: False
        properties:
          app:
            $ref: '#/definitions/app'
            default: {}
            description: The application to run with the 'monado' action
          config:
            type: object
            default: {}
            additionalProperties:
              type: string
            description: Vars that get passed to the build system
  profile:
    default: dbg
    type: string
    description: "Currently supports 'dbg' and 'opt'"
  constants:
    type: array
    default: []
    items:
      type: object
      default: {}
      additionalProperties:
        $ref: '#/definitions/path'
      description: A map of constant names to their set (stringified) values. The value can be destringified at application run-time.
