name: illixr-tests-master

on:
  push:
    branches: [ master ]

env:
  ghcr_token: ${{ secrets.GHCR_TOKEN }}

jobs:
  illixr-tests-master-ubuntu18:
    env:
      distro_ver: 18.04
    runs-on: ubuntu-18.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Extract Branch Name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash

      - name: Run CI (fetch-build-run)
        uses: ILLIXR/github-actions-workflows@v1
        with:
          ghcr_token: ${{ env.ghcr_token }}
          distro_ver: ${{ env.distro_ver }}
          branch     : ${{ steps.extract_branch.outputs.branch }}
  illixr-tests-master-ubuntu20:
    env:
      distro_ver: 20.04
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Extract Branch Name
        id: extract_branch
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        shell: bash

      - name: Run CI (fetch-build-run)
        uses: ILLIXR/github-actions-workflows@v1
        with:
          ghcr_token : ${{ env.ghcr_token }}
          distro_ver : ${{ env.distro_ver }}
          branch     : ${{ steps.extract_branch.outputs.branch }}
