name: illixr-tests-pr

on:
  pull_request:
    branches: [ master ]

jobs:
  illixr-tests-pr-ubuntu18:
    env:
      ghcr_token: ${{ secrets.GHCR_TOKEN }}
      distro_ver: 18.04
    runs-on: ubuntu-18.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run CI (fetch-build-run)
        uses: ILLIXR/github-actions-workflows@v1
        with:
          ghcr_token: ${{ env.ghcr_token }}
          distro_ver: ${{ env.distro_ver }}
  illixr-tests-pr-ubuntu20:
    env:
      ghcr_token: ${{ secrets.GHCR_TOKEN }}
      distro_ver: 20.04
    runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Run CI (fetch-build-run)
        uses: ILLIXR/github-actions-workflows@v1
        with:
          ghcr_token: ${{ env.ghcr_token }}
          distro_ver: ${{ env.distro_ver }}
